### PR TITLE
feat/prettier eslint config

### PR DESCRIPTION
**Pull request by agupta1989**
@redraushan @samanyougarg Please review

it looks like, we will have to manually fix some of eslint issues.

### CODE REVIEW

**Comment by redraushan** [comment]
Hi @agupta1989,
Thanks for the PR. I was going through the `npm run format` script and seems like it's not working properly. It throws the following error for me:

image

**Comment by redraushan** [comment]
Also, if I change the format script to the following, it's working on my mac machine.
```
    "format": "prettier-eslint --eslint-config-path ./.eslintrc.js --write \"src/**/*.js\""
```

**Comment by agupta1989** [comment]
Following changes are pushed:

- Downgraded eslint to 6.4.0 to work with prettier-eslint properly else above error is thrown

- Manually fix some linting issues, added some rules in eslintrc

**Comment by redraushan** [comment]
Hi @agupta1989,
Thanks for the changes, `npm run format` is working perfectly fine. On the other side, latest version of prettier package seems to breaking on `Mac OS X`, and the good news is reverting back to "2.0.2" works correctly. You can find the same issue has been discussed here - [https://github.com/prettier/prettier-atom/issues/725](https://github.com/prettier/prettier-atom/issues/725).

I would request you to please revert and lock the of prettier package version to `"prettier": "2.0.2"`.
I have verified the above version and its working.

**Comment by samanyougarg** [comment]
@agupta1989 Can you please resolve the conflicts and resubmit the PR, please.

**Comment by agupta1989** [comment]
too many conflicts.. closing this PR, will raise another one.

**Pull request closed without merging**
